name: oshinowoa_firebase_gis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.1.0
  syncfusion_flutter_maps: ^19.4.42-beta
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  rename: ^2.0.1
  rxdart: ^0.27.3
  google_maps_flutter: ^2.1.1
  geoflutterfire: ^3.0.2
  geolocator: ^8.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
    - assets/
